### ISSUE TITLE
DAOの整理

### ISSUE THREAD

**Issue by ChikaraIsPower** [Shirahata777/todo-app#2]
Daoの配下のクラスが1クラス1処理になっているのを改めてください。
今パッケージの中にあるクラス群で一つのクラスになれそうです。

entityというパッケージ名と中にあるクラスの内容が乖離しています。
entityというパッケージ名を改めてください。

またクラスの名称も動詞 + 目的語になっており、これはメソッドの命名と被るので適切な命名をしてください

**Comment by Shirahata777** [comment]
こちら修正させていただきました。
・entityクラスは「repository」クラスに変更かつDAO配下へ移動
・メソッドの名前を修正
